# where to store image files.
image_directory = "var/images"

# sqlite database path
database_path = "var/db/image_info.db"

# motion watcher settings
use_motion_watcher = true

# Use image diff monitoring or radar.
motion_watcher_type = "image_diff"
#motion_watcher_type = "radar"

motion_watcher_count = 50
motion_watcher_round_interval_ms = 100

# Image capturer settings (captures images after motion detected)
image_capturer_capture_count = 5
image_capturer_capture_interval_ms = 100

radar_gpio_pin = 17
# radar_gpio_chip_path = "/dev/gpiochip0"

# pick motion detector type / algorithm (yplane_motion_percentile, yplane_boxed_average)
motion_detector_type = "yplane_boxed_average"

# y plane motion detector defaults
yplane_motion_percentile = 0.95
yplane_motion_percentile_threshold = 0.02

# y plane boxed average motion detector settings
yplane_boxed_average_motion_detector_box_size = 25
yplane_boxed_average_motion_detector_percentile = 0.99
yplane_boxed_average_motion_detector_threshold = 0.02

# y plane rolling z settings
use_yplane_rolling_z = true
yplane_rolling_z_alpha = 0.05
yplane_rolling_z_threshold = 2.0

# object detector defaults
object_detector_type = "opencv"

# opencv object detector defaults
opencv_model_config_path = "models/yolov4-tiny.cfg"
opencv_model_weights_path = "models/yolov4-tiny.weights"
opencv_model_names_path = "models/coco.names"
opencv_model_confidence_threshold = 0.15
