[package]
name = "rook_life_watch"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
build = "build.rs"

[features]
default = []
libcamera = []
opencv = ["dep:opencv"]

[dependencies]
anyhow = "1"
image = "0.25"
thiserror = "2"

[build-dependencies]
pkg-config = "0.3"

[dependencies.opencv]
version = "0.95"
default-features = false
features = ["videoio", "imgproc"]
optional = true
